locale                   : "en-US"
site_theme               : "default"
title                    : "H. Craig Melchert"
title_separator          : "-"
name                     : &name "H. Craig Melchert"
description              : &description "Publications, teaching, and lectures of H. Craig Melchert"
url                      : https://hcmelchert.github.io
baseurl                  : ""
repository               : "hcmelchert/hcmelchert.github.io"

author:
  avatar           : "craig.jpg"
  name             : "H. Craig Melchert"
  bio              : "A. Richard Diebold Professor of Indo-European Studies, Emeritus, and Professor of Linguistics, Emeritus"
  employer         : "UCLA"
  email            : "melchert@humnet.ucla.edu"
  academia         : "https://ucla.academia.edu/hcraigmelchert"

breadcrumbs              : false
atom_feed:
  hide                   : true

include:
  - _pages
  - files
exclude:
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - vendor
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
